In [1]:
import pandas as pd 
import duckdb

In [2]:
duckdb.connect("wids_train.db")

### Train data conversion to parquet file

In [ ]:
conn1 = duckdb.connect('wids.db')
query = """
        SELECT * 
        FROM read_csv('TRAIN\TRAIN_FUNCTIONAL_CONNECTOME_MATRICES_new_36P_Pearson.csv')
"""

data = duckdb.execute(query).fetch_df()
data = pd.DataFrame(data)
data.head()

,participant_id,0throw_1thcolumn,0throw_2thcolumn,0throw_3thcolumn,0throw_4thcolumn,0throw_5thcolumn,0throw_6thcolumn,0throw_7thcolumn,0throw_8thcolumn,0throw_9thcolumn,...,195throw_196thcolumn,195throw_197thcolumn,195throw_198thcolumn,195throw_199thcolumn,196throw_197thcolumn,196throw_198thcolumn,196throw_199thcolumn,197throw_198thcolumn,197throw_199thcolumn,198throw_199thcolumn
0,70z8Q2xdTXM3,0.222930,0.527903,0.429966,0.060457,0.566489,0.315342,0.508408,-0.078290,0.525692,...,0.224985,0.397448,0.422966,0.184642,0.305549,0.420349,0.016328,0.561864,0.471170,0.365221
1,WHWymJu6zNZi,0.614765,0.577255,0.496127,0.496606,0.404686,0.439724,0.122590,-0.085452,0.120673,...,0.217546,-0.014549,0.000440,-0.096451,0.454501,0.343916,0.167313,0.607656,0.550623,0.503176
2,4PAQp1M6EyAo,-0.116833,0.458408,0.260703,0.639031,0.769337,0.442528,0.637110,0.192010,0.520379,...,0.342487,-0.021141,-0.037836,0.075069,0.412712,0.292708,0.391005,0.461544,0.508912,0.624232
3,obEacy4Of68I,0.199688,0.752714,0.658283,0.575096,0.692867,0.645789,0.522750,0.412188,0.530843,...,0.103562,-0.178313,0.210983,-0.018666,0.436313,0.592982,0.216205,0.341272,0.440313,0.558193
4,s7WzzDcmDOhF,0.227321,0.613268,0.621447,0.562673,0.736709,0.589813,0.266676,0.359668,0.300771,...,-0.164956,0.007064,-0.120904,-0.488095,0.493575,-0.215361,0.210685,0.055850,0.119065,0.108273

In [4]:
connect2 = duckdb.connect('wids_train.db')
data2 = connect2.execute("SELECT * FROM read_xlsx('TRAIN/TRAIN_QUANTITATIVE_METADATA_new.xlsx')").fetch_df()
data2 = pd.DataFrame(data2)
data2.head()

,participant_id,EHQ_EHQ_Total,ColorVision_CV_Score,APQ_P_APQ_P_CP,APQ_P_APQ_P_ID,APQ_P_APQ_P_INV,APQ_P_APQ_P_OPD,APQ_P_APQ_P_PM,APQ_P_APQ_P_PP,SDQ_SDQ_Conduct_Problems,SDQ_SDQ_Difficulties_Total,SDQ_SDQ_Emotional_Problems,SDQ_SDQ_Externalizing,SDQ_SDQ_Generating_Impact,SDQ_SDQ_Hyperactivity,SDQ_SDQ_Internalizing,SDQ_SDQ_Peer_Problems,SDQ_SDQ_Prosocial,MRI_Track_Age_at_Scan
0,00aIpNTbG5uh,100.00,13.0,3.0,15.0,44.0,14.0,20.0,27.0,3.0,17.0,4.0,11.0,5.0,8.0,6.0,2.0,9.0,14.274127
1,00fV0OyyoLfw,92.27,14.0,3.0,12.0,35.0,25.0,28.0,30.0,5.0,20.0,4.0,13.0,5.0,8.0,7.0,3.0,8.0,NaN
2,04X1eiS79T4B,86.67,14.0,3.0,21.0,37.0,18.0,26.0,28.0,3.0,24.0,7.0,10.0,10.0,7.0,14.0,7.0,7.0,13.463381
3,05ocQutkURd6,93.34,14.0,3.0,11.0,42.0,15.0,20.0,28.0,0.0,5.0,0.0,3.0,0.0,3.0,2.0,2.0,6.0,9.572553
4,06YUNBA9ZRLq,0.00,14.0,8.0,12.0,35.0,22.0,12.0,24.0,6.0,23.0,7.0,15.0,8.0,9.0,8.0,1.0,4.0,6.654574

In [8]:
connect3 = duckdb.connect('wids_train.db')
data3 = connect3.execute("SELECT * FROM read_xlsx('TRAIN/TRAIN_CATEGORICAL_METADATA_new.xlsx')").fetch_df()
data3 = pd.DataFrame(data3)
data3.head()

,participant_id,Basic_Demos_Enroll_Year,Basic_Demos_Study_Site,PreInt_Demos_Fam_Child_Ethnicity,PreInt_Demos_Fam_Child_Race,MRI_Track_Scan_Location,Barratt_Barratt_P1_Edu,Barratt_Barratt_P1_Occ,Barratt_Barratt_P2_Edu,Barratt_Barratt_P2_Occ
0,00aIpNTbG5uh,2019.0,4.0,1.0,0.0,3.0,21.0,45.0,NaN,NaN
1,00fV0OyyoLfw,2017.0,1.0,0.0,9.0,2.0,21.0,0.0,21.0,45.0
2,04X1eiS79T4B,2017.0,1.0,1.0,2.0,2.0,9.0,0.0,NaN,NaN
3,05ocQutkURd6,2018.0,1.0,3.0,8.0,2.0,18.0,10.0,18.0,0.0
4,06YUNBA9ZRLq,2018.0,1.0,0.0,1.0,2.0,12.0,0.0,NaN,NaN

In [ ]:
for col in data3.columns[1:]:  
    if pd.api.types.is_float_dtype(data3[col]):
        if (data3[col] % 1 == 0).all():  
            data3[col] = data3[col].astype(int)

In [12]:
data3.head()

,participant_id,Basic_Demos_Enroll_Year,Basic_Demos_Study_Site,PreInt_Demos_Fam_Child_Ethnicity,PreInt_Demos_Fam_Child_Race,MRI_Track_Scan_Location,Barratt_Barratt_P1_Edu,Barratt_Barratt_P1_Occ,Barratt_Barratt_P2_Edu,Barratt_Barratt_P2_Occ
0,00aIpNTbG5uh,2019,4,1.0,0.0,3.0,21.0,45.0,NaN,NaN
1,00fV0OyyoLfw,2017,1,0.0,9.0,2.0,21.0,0.0,21.0,45.0
2,04X1eiS79T4B,2017,1,1.0,2.0,2.0,9.0,0.0,NaN,NaN
3,05ocQutkURd6,2018,1,3.0,8.0,2.0,18.0,10.0,18.0,0.0
4,06YUNBA9ZRLq,2018,1,0.0,1.0,2.0,12.0,0.0,NaN,NaN

In [14]:
connect4 = duckdb.connect('wids_train.db')
data4 = connect4.execute("SELECT * FROM read_csv('NILEARN_805TRAINING_ADHD.csv')").fetch_df()
data4.drop(columns='column000', axis=1, inplace=True)
data4 = pd.DataFrame(data4)

data4.head()

,participant_id,PCA1,PCA2,PCA3,PCA4,PCA5,PCA6,PCA7,PCA8,PCA9,...,PCA796,PCA797,PCA798,PCA799,PCA800,PCA801,PCA802,PCA803,PCA804,PCA805
0,70z8Q2xdTXM3,1.235597,-0.923462,0.738579,-0.549391,0.255479,0.626539,-1.427647,-0.053532,-1.197277,...,-0.031031,0.061532,0.332824,0.103205,-0.437093,0.087633,0.154107,0.407039,0.089164,0.224855
1,WHWymJu6zNZi,2.013580,0.101673,0.028803,-0.104860,0.586899,-1.328468,-0.661806,-0.865374,-0.079131,...,0.018690,0.014816,-0.237873,0.137496,-0.402823,0.211166,-0.407026,0.339214,0.312276,0.278638
2,4PAQp1M6EyAo,1.445007,1.342929,1.024136,-0.754537,-0.451848,0.295041,0.267448,0.834409,0.231763,...,-0.020217,-0.100364,-0.350987,-0.001915,0.932559,0.185211,-0.145835,0.312283,0.207280,-0.178426
3,obEacy4Of68I,-2.367461,-0.649463,0.815196,-0.776162,0.451472,-0.912395,0.342284,0.411752,0.670772,...,-0.439869,-0.535651,0.403955,0.058315,-0.234602,-0.670253,0.227380,0.322604,0.230284,-0.262748
4,s7WzzDcmDOhF,0.525255,0.769687,0.608093,-0.529924,1.209092,-0.718644,-0.409689,-0.463879,-0.232541,...,0.363037,-0.115642,-0.007847,0.189744,0.028457,-0.163523,-0.106370,0.396455,-0.250403,-0.131111

In [13]:
connect5 = duckdb.connect('wids_train.db')
data5 = connect5.execute("SELECT * FROM read_xlsx('TRAIN/TRAINING_SOLUTIONS.xlsx')").fetch_df()
data5 = pd.DataFrame(data5)
data5.head()

  participant_id  ADHD_Outcome  Sex_F
0   UmrK0vMLopoR           1.0    1.0
1   CPaeQkhcjg7d           1.0    0.0
2   Nb4EetVPm3gs           1.0    0.0
3   p4vPhVu91o4b           1.0    1.0
4   M09PXs7arQ5E           1.0    1.0

In [14]:
data5[["ADHD_Outcome", "Sex_F"]] = data5[["ADHD_Outcome", "Sex_F"]].astype(int)
data5.head()

  participant_id  ADHD_Outcome  Sex_F
0   UmrK0vMLopoR             1      1
1   CPaeQkhcjg7d             1      0
2   Nb4EetVPm3gs             1      0
3   p4vPhVu91o4b             1      1
4   M09PXs7arQ5E             1      1

In [15]:
query = """
SELECT *
FROM data4
JOIN data5 USING (participant_id)
"""

# Execute the query
result_df = duckdb.query(query).to_df()
result_df

,participant_id,PCA1,PCA2,PCA3,PCA4,PCA5,PCA6,PCA7,PCA8,PCA9,...,PCA798,PCA799,PCA800,PCA801,PCA802,PCA803,PCA804,PCA805,ADHD_Outcome,Sex_F
0,WHWymJu6zNZi,2.013580,0.101673,0.028803,-0.104860,0.586899,-1.328468,-0.661806,-0.865374,-0.079131,...,-0.237873,0.137496,-0.402823,0.211166,-0.407026,0.339214,0.312276,0.278638,1,1
1,4PAQp1M6EyAo,1.445007,1.342929,1.024136,-0.754537,-0.451848,0.295041,0.267448,0.834409,0.231763,...,-0.350987,-0.001915,0.932559,0.185211,-0.145835,0.312283,0.207280,-0.178426,1,1
2,obEacy4Of68I,-2.367461,-0.649463,0.815196,-0.776162,0.451472,-0.912395,0.342284,0.411752,0.670772,...,0.403955,0.058315,-0.234602,-0.670253,0.227380,0.322604,0.230284,-0.262748,1,1
3,s7WzzDcmDOhF,0.525255,0.769687,0.608093,-0.529924,1.209092,-0.718644,-0.409689,-0.463879,-0.232541,...,-0.007847,0.189744,0.028457,-0.163523,-0.106370,0.396455,-0.250403,-0.131111,1,1
4,sId1cQF5F22m,-0.186628,-1.883103,-0.823613,0.649669,0.979945,-1.613828,-0.145874,-2.080809,-0.279470,...,-0.315101,-0.160558,-0.148128,-0.107537,-0.178859,-0.217092,-0.070236,-0.094620,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1208,7CkP21xwNO4M,-0.149221,0.080352,-1.510449,2.884118,-1.695771,1.690277,-0.019980,0.405372,0.474779,...,0.200907,0.076939,0.124117,-0.482325,-0.043307,0.127455,0.114480,-0.281614,0,0
1209,CgU9hobPWpRo,0.859386,0.826223,0.777378,0.354097,0.042793,0.737905,-0.705106,0.407417,1.659661,...,-0.235722,-0.508680,0.592588,-0.442193,-0.325241,-0.093372,-0.109044,0.249349,1,0
1210,HG0Pu8QHXKut,-0.642744,1.138665,-0.403727,-0.709896,-0.204461,1.021731,0.282794,-0.145601,0.977239,...,0.365295,-0.259930,-0.177006,0.060173,-0.574742,0.226961,-0.240469,0.009775,0,1
1211,7XJZtiSVaOtC,0.258140,-0.303577,0.179816,0.773369,-2.146965,-0.817172,1.041139,0.172254,0.108168,...,0.171554,-0.062525,0.093776,0.234867,0.202990,0.285512,0.218937,0.268564,1,0
1212,G0AEGe59Tg3w,-2.288781,0.227619,0.410805,-0.994153,0.625904,0.472245,0.183028,-1.603913,0.329278,...,-0.033293,0.206590,0.469203,0.867679,0.113586,-0.459814,0.234418,-0.055967,0,0

In [16]:
query = """
SELECT *
FROM data2
JOIN data3 USING (participant_id)
JOIN data5 USING (participant_id)
"""

# Execute the query
supplimentary_df = duckdb.query(query).to_df()
supplimentary_df

,participant_id,EHQ_EHQ_Total,ColorVision_CV_Score,APQ_P_APQ_P_CP,APQ_P_APQ_P_ID,APQ_P_APQ_P_INV,APQ_P_APQ_P_OPD,APQ_P_APQ_P_PM,APQ_P_APQ_P_PP,SDQ_SDQ_Conduct_Problems,...,Basic_Demos_Study_Site,PreInt_Demos_Fam_Child_Ethnicity,PreInt_Demos_Fam_Child_Race,MRI_Track_Scan_Location,Barratt_Barratt_P1_Edu,Barratt_Barratt_P1_Occ,Barratt_Barratt_P2_Edu,Barratt_Barratt_P2_Occ,ADHD_Outcome,Sex_F
0,00aIpNTbG5uh,100.00,13.0,3.0,15.0,44.0,14.0,20.0,27.0,3.0,...,4,1.0,0.0,3.0,21.0,45.0,NaN,NaN,1,0
1,00fV0OyyoLfw,92.27,14.0,3.0,12.0,35.0,25.0,28.0,30.0,5.0,...,1,0.0,9.0,2.0,21.0,0.0,21.0,45.0,1,0
2,05ocQutkURd6,93.34,14.0,3.0,11.0,42.0,15.0,20.0,28.0,0.0,...,1,3.0,8.0,2.0,18.0,10.0,18.0,0.0,0,1
3,06YUNBA9ZRLq,0.00,14.0,8.0,12.0,35.0,22.0,12.0,24.0,6.0,...,1,0.0,1.0,2.0,12.0,0.0,NaN,NaN,1,0
4,0cduHhwrQN4r,-100.00,14.0,5.0,16.0,36.0,19.0,13.0,22.0,6.0,...,1,0.0,0.0,2.0,18.0,25.0,15.0,40.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1208,7CkP21xwNO4M,13.34,14.0,6.0,11.0,48.0,26.0,10.0,30.0,3.0,...,3,0.0,1.0,3.0,18.0,30.0,15.0,30.0,0,0
1209,CgU9hobPWpRo,-53.34,14.0,3.0,9.0,46.0,22.0,10.0,28.0,6.0,...,3,0.0,0.0,2.0,18.0,0.0,NaN,NaN,1,0
1210,7XJZtiSVaOtC,80.00,14.0,3.0,15.0,36.0,16.0,11.0,22.0,2.0,...,1,0.0,0.0,3.0,18.0,30.0,18.0,30.0,1,0
1211,HG0Pu8QHXKut,33.35,12.0,4.0,16.0,42.0,15.0,12.0,30.0,0.0,...,1,1.0,2.0,2.0,15.0,40.0,9.0,20.0,0,1
1212,G0AEGe59Tg3w,91.14,14.0,3.0,13.0,42.0,15.0,14.0,28.0,0.0,...,1,1.0,2.0,2.0,18.0,40.0,21.0,40.0,0,0

In [16]:
duckdb.register('result_table', result_df)
duckdb.query("COPY result_table TO 'nilearn_805FULL_TRAINING.csv' (FORMAT 'csv', HEADER)")

In [17]:
duckdb.register('result_table', supplimentary_df)
duckdb.query("COPY result_table TO 'suplimentary_train.csv' (FORMAT 'csv', HEADER)")

### Test data conversion into parquet file

In [8]:
connect_test = duckdb.connect('wids_train.db')
test_data = connect_test.execute("SELECT * FROM read_csv('TEST/TEST_FUNCTIONAL_CONNECTOME_MATRICES.csv')").fetch_df()
test_data = pd.DataFrame(test_data)
test_data.head()

,participant_id,0throw_1thcolumn,0throw_2thcolumn,0throw_3thcolumn,0throw_4thcolumn,0throw_5thcolumn,0throw_6thcolumn,0throw_7thcolumn,0throw_8thcolumn,0throw_9thcolumn,...,195throw_196thcolumn,195throw_197thcolumn,195throw_198thcolumn,195throw_199thcolumn,196throw_197thcolumn,196throw_198thcolumn,196throw_199thcolumn,197throw_198thcolumn,197throw_199thcolumn,198throw_199thcolumn
0,Cfwaf5FX7jWK,0.548480,0.713607,0.557319,0.524369,0.693364,0.770032,0.724406,0.390118,0.547912,...,0.080423,-0.054581,-0.088163,-0.028574,0.444847,0.350149,-0.012601,0.665750,0.560565,0.555732
1,vhGrzmvA3Hjq,0.427740,0.363022,0.402862,0.363003,0.534558,0.345347,0.409471,0.303328,0.402515,...,0.198009,-0.000724,0.083122,0.033043,0.687497,0.306229,0.717485,0.461809,0.559632,0.350027
2,ULliyEXjy4OV,0.139572,0.390106,-0.087041,0.196852,0.088148,0.023843,0.381782,0.068979,0.377488,...,0.051319,0.023630,-0.056819,0.117396,0.576086,0.517831,0.527044,0.605038,0.609856,0.750987
3,LZfeAb1xMtql,0.133561,0.778326,0.416355,0.471840,0.568460,0.633660,0.501113,0.345461,0.467943,...,0.046183,-0.238962,0.121868,-0.260970,0.646818,0.594902,0.608156,0.595459,0.683189,0.542296
4,EnFOUv0YK1RG,0.126699,0.575446,0.509422,0.363193,0.427544,0.449924,0.451796,0.223927,0.298248,...,0.315734,0.002234,0.290791,0.344149,0.480214,0.539824,0.447322,0.293088,0.148529,0.539823

In [3]:
connect_test2 = duckdb.connect('wids_train.db')
test_data2 = connect_test2.execute("SELECT * FROM read_xlsx('TEST/TEST_QUANTITATIVE_METADATA.xlsx')").fetch_df()
test_data2 = pd.DataFrame(test_data2)
test_data2.head()

,participant_id,EHQ_EHQ_Total,ColorVision_CV_Score,APQ_P_APQ_P_CP,APQ_P_APQ_P_ID,APQ_P_APQ_P_INV,APQ_P_APQ_P_OPD,APQ_P_APQ_P_PM,APQ_P_APQ_P_PP,SDQ_SDQ_Conduct_Problems,SDQ_SDQ_Difficulties_Total,SDQ_SDQ_Emotional_Problems,SDQ_SDQ_Externalizing,SDQ_SDQ_Generating_Impact,SDQ_SDQ_Hyperactivity,SDQ_SDQ_Internalizing,SDQ_SDQ_Peer_Problems,SDQ_SDQ_Prosocial,MRI_Track_Age_at_Scan
0,Cfwaf5FX7jWK,60.03,14.0,5.0,16.0,41.0,19.0,11.0,26.0,2.0,12.0,3.0,9.0,2.0,7.0,3.0,0.0,8.0,8.992813
1,vhGrzmvA3Hjq,86.71,12.0,3.0,13.0,43.0,18.0,15.0,28.0,2.0,16.0,8.0,5.0,7.0,3.0,11.0,3.0,9.0,12.324093
2,ULliyEXjy4OV,26.68,13.0,3.0,14.0,36.0,16.0,14.0,25.0,1.0,7.0,1.0,6.0,1.0,5.0,1.0,0.0,9.0,7.770933
3,LZfeAb1xMtql,93.38,13.0,3.0,19.0,41.0,17.0,18.0,27.0,4.0,15.0,4.0,10.0,8.0,6.0,5.0,1.0,6.0,9.304814
4,EnFOUv0YK1RG,-93.38,14.0,3.0,13.0,42.0,19.0,16.0,28.0,2.0,18.0,6.0,12.0,5.0,10.0,6.0,0.0,10.0,8.261350

In [4]:
connect_test3 = duckdb.connect('wids_train.db')
test_data3 = connect_test3.execute("SELECT * FROM read_xlsx('TEST/TEST_CATEGORICAL.xlsx')").fetch_df()
test_data3 = pd.DataFrame(test_data3)
test_data3.head()

,participant_id,Basic_Demos_Enroll_Year,Basic_Demos_Study_Site,PreInt_Demos_Fam_Child_Ethnicity,PreInt_Demos_Fam_Child_Race,MRI_Track_Scan_Location,Barratt_Barratt_P1_Edu,Barratt_Barratt_P1_Occ,Barratt_Barratt_P2_Edu,Barratt_Barratt_P2_Occ
0,Cfwaf5FX7jWK,2022.0,4.0,0.0,0.0,4.0,21.0,30.0,18.0,30.0
1,vhGrzmvA3Hjq,2023.0,4.0,0.0,0.0,4.0,21.0,45.0,NaN,30.0
2,ULliyEXjy4OV,2022.0,4.0,0.0,0.0,4.0,21.0,40.0,18.0,40.0
3,LZfeAb1xMtql,2022.0,4.0,0.0,0.0,3.0,21.0,45.0,21.0,45.0
4,EnFOUv0YK1RG,2022.0,4.0,2.0,0.0,4.0,18.0,0.0,21.0,45.0

In [5]:
test_query = """
SELECT *
FROM test_data2 
JOIN test_data3 USING (participant_id)
"""

# Execute the query
result_df_test = duckdb.query(test_query).to_df()
result_df_test.head()

,participant_id,EHQ_EHQ_Total,ColorVision_CV_Score,APQ_P_APQ_P_CP,APQ_P_APQ_P_ID,APQ_P_APQ_P_INV,APQ_P_APQ_P_OPD,APQ_P_APQ_P_PM,APQ_P_APQ_P_PP,SDQ_SDQ_Conduct_Problems,...,MRI_Track_Age_at_Scan,Basic_Demos_Enroll_Year,Basic_Demos_Study_Site,PreInt_Demos_Fam_Child_Ethnicity,PreInt_Demos_Fam_Child_Race,MRI_Track_Scan_Location,Barratt_Barratt_P1_Edu,Barratt_Barratt_P1_Occ,Barratt_Barratt_P2_Edu,Barratt_Barratt_P2_Occ
0,Cfwaf5FX7jWK,60.03,14.0,5.0,16.0,41.0,19.0,11.0,26.0,2.0,...,8.992813,2022.0,4.0,0.0,0.0,4.0,21.0,30.0,18.0,30.0
1,vhGrzmvA3Hjq,86.71,12.0,3.0,13.0,43.0,18.0,15.0,28.0,2.0,...,12.324093,2023.0,4.0,0.0,0.0,4.0,21.0,45.0,NaN,30.0
2,ULliyEXjy4OV,26.68,13.0,3.0,14.0,36.0,16.0,14.0,25.0,1.0,...,7.770933,2022.0,4.0,0.0,0.0,4.0,21.0,40.0,18.0,40.0
3,LZfeAb1xMtql,93.38,13.0,3.0,19.0,41.0,17.0,18.0,27.0,4.0,...,9.304814,2022.0,4.0,0.0,0.0,3.0,21.0,45.0,21.0,45.0
4,EnFOUv0YK1RG,-93.38,14.0,3.0,13.0,42.0,19.0,16.0,28.0,2.0,...,8.261350,2022.0,4.0,2.0,0.0,4.0,18.0,0.0,21.0,45.0

In [6]:
duckdb.register('test_result_table', result_df_test)
duckdb.query("COPY test_result_table TO 'suplimentary_test.csv' (FORMAT 'csv', HEADER)")

In [17]:
result_df_test

,participant_id,EHQ_EHQ_Total,ColorVision_CV_Score,APQ_P_APQ_P_CP,APQ_P_APQ_P_ID,APQ_P_APQ_P_INV,APQ_P_APQ_P_OPD,APQ_P_APQ_P_PM,APQ_P_APQ_P_PP,SDQ_SDQ_Conduct_Problems,...,MRI_Track_Age_at_Scan,Basic_Demos_Enroll_Year,Basic_Demos_Study_Site,PreInt_Demos_Fam_Child_Ethnicity,PreInt_Demos_Fam_Child_Race,MRI_Track_Scan_Location,Barratt_Barratt_P1_Edu,Barratt_Barratt_P1_Occ,Barratt_Barratt_P2_Edu,Barratt_Barratt_P2_Occ
0,Cfwaf5FX7jWK,60.03,14.0,5.0,16.0,41.0,19.0,11.0,26.0,2.0,...,8.992813,2022.0,4.0,0.0,0.0,4.0,21.0,30.0,18.0,30.0
1,vhGrzmvA3Hjq,86.71,12.0,3.0,13.0,43.0,18.0,15.0,28.0,2.0,...,12.324093,2023.0,4.0,0.0,0.0,4.0,21.0,45.0,NaN,30.0
2,ULliyEXjy4OV,26.68,13.0,3.0,14.0,36.0,16.0,14.0,25.0,1.0,...,7.770933,2022.0,4.0,0.0,0.0,4.0,21.0,40.0,18.0,40.0
3,LZfeAb1xMtql,93.38,13.0,3.0,19.0,41.0,17.0,18.0,27.0,4.0,...,9.304814,2022.0,4.0,0.0,0.0,3.0,21.0,45.0,21.0,45.0
4,EnFOUv0YK1RG,-93.38,14.0,3.0,13.0,42.0,19.0,16.0,28.0,2.0,...,8.261350,2022.0,4.0,2.0,0.0,4.0,18.0,0.0,21.0,45.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,cRySmCadYFRO,87.84,13.0,3.0,14.0,42.0,15.0,10.0,28.0,1.0,...,7.210586,2023.0,4.0,0.0,8.0,4.0,21.0,25.0,15.0,NaN
300,fJ18nx0flUWU,91.18,14.0,3.0,18.0,38.0,16.0,16.0,29.0,0.0,...,7.180469,2022.0,4.0,0.0,4.0,3.0,21.0,35.0,21.0,35.0
301,ThzfJlzfC5zm,77.84,14.0,3.0,23.0,44.0,16.0,14.0,20.0,NaN,...,14.771617,2022.0,4.0,0.0,0.0,4.0,21.0,35.0,18.0,45.0
302,t6Yc857Xm0G1,73.37,14.0,3.0,11.0,33.0,20.0,26.0,24.0,4.0,...,15.437371,2022.0,4.0,1.0,0.0,4.0,18.0,40.0,15.0,15.0
303,GtKTU9RdYH88,83.38,13.0,3.0,12.0,45.0,15.0,10.0,28.0,2.0,...,9.184462,2022.0,4.0,0.0,0.0,4.0,21.0,45.0,18.0,45.0

### **Join the selected categorical columns with the reduced 800 features from PCA.**

In [3]:
connect_cat = duckdb.connect('wids_train.db')
train_cat = connect_cat.execute("SELECT * FROM read_csv('cat_columns.csv')").fetch_df()
train_cat = pd.DataFrame(train_cat)
train_cat.head()

,column00,participant_id,SDQ_SDQ_Hyperactivity,SDQ_SDQ_Externalizing,SDQ_SDQ_Difficulties_Total,SDQ_SDQ_Generating_Impact,SDQ_SDQ_Prosocial,SDQ_SDQ_Emotional_Problems,Prosocial_x_Hyperactivity,Impact_x_Hyperactivity,Prosocial_x_Externalizing,Conduct_x_Hyperactivity,Conduct_x_Externalizing
0,0,CPaeQkhcjg7d,8.0,8.0,18.0,7.0,5.0,6.0,40.0,56.0,40.0,0.0,0.0
1,1,Nb4EetVPm3gs,7.0,8.0,14.0,5.0,9.0,2.0,63.0,35.0,72.0,7.0,8.0
2,2,p4vPhVu91o4b,10.0,16.0,24.0,9.0,6.0,4.0,60.0,90.0,96.0,60.0,96.0
3,3,M09PXs7arQ5E,10.0,11.0,18.0,4.0,9.0,4.0,90.0,40.0,99.0,10.0,11.0
4,4,tBGXkEdv2cp7,8.0,12.0,17.0,9.0,3.0,0.0,24.0,72.0,36.0,32.0,48.0

In [4]:
connect_reduced = duckdb.connect('wids_train.db')
train_reduced = connect_reduced.execute("SELECT * FROM read_csv('800Reduced_functional_brain.csv')").fetch_df()
train_reduced = pd.DataFrame(train_reduced)
train_reduced.head()

,participant_id,PCA_1,PCA_2,PCA_3,PCA_4,PCA_5,PCA_6,PCA_7,PCA_8,PCA_9,...,PCA_793,PCA_794,PCA_795,PCA_796,PCA_797,PCA_798,PCA_799,PCA_800,ADHD_Outcome,Sex_F
0,WHWymJu6zNZi,-0.437470,0.495804,-0.018796,0.018182,0.151769,-0.118468,0.157985,-0.026742,-0.034691,...,-0.117554,0.117799,0.166419,-0.029062,-0.026939,-0.151799,-0.115299,0.138108,1,1
1,4PAQp1M6EyAo,-0.041330,0.585298,0.181564,0.061549,0.075908,-0.017260,-0.076878,0.164383,0.096225,...,0.074839,-0.095578,0.396827,0.128239,-0.020148,-0.308369,0.209124,0.001301,1,1
2,obEacy4Of68I,0.149834,-0.527528,-0.032539,-0.022992,0.043623,-0.167571,-0.095505,0.068575,-0.029254,...,0.006301,0.143478,0.174921,-0.022046,-0.271195,-0.290589,-0.015969,0.155544,1,1
3,s7WzzDcmDOhF,-0.486916,-0.016741,0.227893,0.003209,0.142476,-0.197946,-0.178693,0.070241,-0.052145,...,0.007448,-0.077505,0.016023,-0.165263,-0.069719,-0.207660,0.215799,-0.112701,1,1
4,sId1cQF5F22m,-0.908737,-0.295869,-0.396560,0.052166,0.098134,-0.029718,0.300825,0.174097,0.167968,...,-0.199443,0.035550,0.059610,0.134219,-0.135777,-0.107039,-0.044250,-0.034434,0,0

In [5]:
#Merge teh reduced daataframe s
reduced_train_query = """
SELECT *
FROM train_cat
JOIN train_reduced USING (participant_id)
"""

# Execute the query
result_df_reduced = duckdb.query(reduced_train_query).to_df()

duckdb.register('train_reduced_table', result_df_reduced)
duckdb.query("COPY train_reduced_table TO '802TRAIN_FUNCTIONAL.csv' (FORMAT 'csv', HEADER)")

### **Merge the selected columns in quantitative testing data excluding the functional connectom ematrices**

In [6]:
quant_test = duckdb.connect('wids_train.db')
test_quant = quant_test.execute("SELECT * FROM read_csv('test_quantitative_cols.csv')").fetch_df()
test_quant = pd.DataFrame(test_quant)
test_quant.head()

,column00,participant_id,SDQ_SDQ_Hyperactivity,SDQ_SDQ_Externalizing,SDQ_SDQ_Difficulties_Total,SDQ_SDQ_Generating_Impact,SDQ_SDQ_Prosocial,SDQ_SDQ_Emotional_Problems,Prosocial_x_Hyperactivity,Impact_x_Hyperactivity,Prosocial_x_Externalizing,Conduct_x_Hyperactivity,Conduct_x_Externalizing
0,0,Cfwaf5FX7jWK,7.0,9.0,12.0,2.0,8.0,3.0,56.0,14.0,72.0,14.0,18.0
1,1,vhGrzmvA3Hjq,3.0,5.0,16.0,7.0,9.0,8.0,27.0,21.0,45.0,6.0,10.0
2,2,ULliyEXjy4OV,5.0,6.0,7.0,1.0,9.0,1.0,45.0,5.0,54.0,5.0,6.0
3,3,LZfeAb1xMtql,6.0,10.0,15.0,8.0,6.0,4.0,36.0,48.0,60.0,24.0,40.0
4,4,EnFOUv0YK1RG,10.0,12.0,18.0,5.0,10.0,6.0,100.0,50.0,120.0,20.0,24.0

In [7]:
connect_cat800 = duckdb.connect('wids_train.db')
test_cat800 = connect_cat800.execute("SELECT * FROM read_csv('800Test_functional.csv')").fetch_df()
test_cat800 = pd.DataFrame(test_cat800)
test_cat800.head()

,participant_id,PCA_1,PCA_2,PCA_3,PCA_4,PCA_5,PCA_6,PCA_7,PCA_8,PCA_9,...,PCA_791,PCA_792,PCA_793,PCA_794,PCA_795,PCA_796,PCA_797,PCA_798,PCA_799,PCA_800
0,Cfwaf5FX7jWK,4.401346,1.342780,-1.203501,0.953116,-0.574720,-0.247623,-1.724452,-0.535627,-1.290130,...,0.019540,0.022110,0.084490,-0.055141,0.024828,0.245408,-0.319061,-0.052508,0.041452,0.279019
1,vhGrzmvA3Hjq,4.922339,0.215453,-0.436138,0.754598,-1.736812,-0.041890,-1.845311,0.592715,-0.651316,...,-0.105377,0.165300,0.069548,0.073925,-0.114144,0.226581,-0.117483,-0.152452,0.271804,0.187377
2,ULliyEXjy4OV,4.800096,0.437278,-1.069556,-0.678842,-1.079107,-0.199143,-1.624927,-0.345196,-0.964932,...,0.321049,0.313655,-0.044684,-0.069610,0.017300,-0.091910,-0.094051,-0.220670,0.048333,0.005753
3,LZfeAb1xMtql,5.119175,1.366094,-1.559780,0.211515,-1.214255,0.343195,-1.674086,-0.254507,-1.088226,...,-0.131000,-0.222059,0.137215,-0.149780,-0.149823,0.192303,0.027688,-0.295967,0.367888,0.151219
4,EnFOUv0YK1RG,4.321010,2.703321,0.072719,0.387173,-0.710631,-0.468188,-1.500822,0.333436,-1.064352,...,0.032714,-0.015052,-0.071156,-0.071749,0.101099,0.284278,-0.165269,-0.119011,0.405289,0.198105

In [8]:
reduced_test_query = """
SELECT *
FROM test_quant
JOIN test_cat800 USING (participant_id)
"""

# Execute the query
test_df_reduced = duckdb.query(reduced_test_query).to_df()

duckdb.register('test_reduced_table', test_df_reduced)
duckdb.query("COPY test_reduced_table TO '802FTEST_FUNCTIONAL.csv' (FORMAT 'csv', HEADER)")

###